pub mod corpus_embedding;
pub mod corpus_index;
pub mod corpus_question;
pub mod corpus_window;
pub mod diagnostic;
pub mod enrollment_guidance;
pub mod library_metadata;
pub mod library_read;
pub mod meeting;
pub mod meeting_coordination;
pub mod meeting_deletion;
pub mod meeting_title;
pub mod note_generation;
pub mod note_projection;
#[cfg(target_os = "macos")]
mod note_projector_process;
pub mod operation_store;
pub mod operations;
#[cfg(target_os = "macos")]
pub mod profile_lifecycle;
pub mod protocol;
pub mod recovery;
pub mod reducer;
pub mod retention;
pub mod runtime;
#[cfg(target_os = "macos")]
pub mod sitting_evidence;
pub mod storage;
pub mod supervision;
pub mod transcript_restoration;
